// Generated by EclipseP5Exporter: Wed Nov 28 13:58:07 CST 2012


import javax.swing.JFrame;


	
	GraphicsRunner()
	{
		super("Graphics Runner");
		setSize(800,600);

		getContentPane().add(new Tree());

		setVisible(true);

		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}

	static void main( String args[] )
	{
		GraphicsRunner run = new GraphicsRunner();
	}

